### PR TITLE
Feature Addition: ExecuteCommand

### PR DESCRIPTION
**Pull request by ajc-osl**
Added ability to execute an arbitrary command string on controller from EPICS as per Aerotech request.
Limited to 40 characters by EPICS.

### CODE REVIEW

**Comment by MarkRivers** [comment]
I don't understand why you say it is limited to 40 characters by EPICS.  You can use a waveform record with FTVL=CHAR or an lso record to send strings that are much longer than 40 characters.

**Comment by kmpeters** [comment]
Examples of using waveforms with FTVL=CHAR can be found in areaDetector:

https://github.com/areaDetector/ADCore/blob/956dbbbdcb49c6bf25608533107f6041a09470b3/ADApp/Db/NDFile.template#L12-L20

**Comment by ajc-osl** [comment]
Thanks for the input guys, I'll make the suggested change.

**Comment by prjemian** [comment]
The name `Feature` is ambiguous.  Please edit the name of this pull request to reflect what feature it addresses.

**Review by rakaerotech — APPROVED** [review]
Changes look good from Aerotech's perspective.

**Review by prjemian — CHANGES_REQUESTED** [review]
Please rename the PR _before_ merge.

**Comment by kmpeters** [comment]
@prjemian are you happy with the new title?

**Pull request merged**
