### PR TITLE
Use PROD_SYS_LIBS_Linux and remove the static build workaround

### LINKED ISSUE #21: Use PROD_SYS_LIBS instead of PROD_LIBS for Automation1 libraries
Use ``PROD_SYS_LIBS`` instead of ``PROD_LIBS`` for Automation1 libraries so the decision to link statically or dynamically can be made on a module-by-module basis, since base and all support modules have both .a and .so files.

This issue is necessary because I merged #20 and closed issue #17 prematurely.

### PR DESCRIPTION
**Pull request by kmpeters**
Fixes #21

### CODE REVIEW

**Comment by kmpeters** [comment]
With the changes in #22...

**EPICS base**: ``SHARED_LIBRARIES=YES`` and ``STATIC_BUILD=NO``
**motorAutomation1**: no shared/static overrides
**Result**: automation1 IOC depends on all the shared libraries

<details>
  <summary>$ ldd iocs/automation1IOC/bin/linux-x86_64/automation1</summary>

	linux-vdso.so.1 (0x00007ffeaa982000)
	libAutomation1.so => /home/username/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libAutomation1.so (0x00007ff83b9fc000)
	libmotor.so => /home/username/epics/motor-devel/current/motor/lib/linux-x86_64/libmotor.so (0x00007ff83b7db000)
	libasyn.so => /home/username/epics/motor-devel/support/asyn-R4-42/lib/linux-x86_64/libasyn.so (0x00007ff83b53c000)
	libbusy.so => /home/username/epics/motor-devel/support/busy-R1-7-3/lib/linux-x86_64/libbusy.so (0x00007ff83b332000)
	libseq.so => /home/username/epics/motor-devel/support/seq-2-2-9/lib/linux-x86_64/libseq.so (0x00007ff83b122000)
	libpv.so => /home/username/epics/motor-devel/support/seq-2-2-9/lib/linux-x86_64/libpv.so (0x00007ff83af1e000)
	libdbRecStd.so.3.21.0 => /home/username/epics/base-7.0.6.1/lib/linux-x86_64/libdbRecStd.so.3.21.0 (0x00007ff83acd8000)
	libdbCore.so.3.21.0 => /home/username/epics/base-7.0.6.1/lib/linux-x86_64/libdbCore.so.3.21.0 (0x00007ff83aa43000)
	libca.so.4.14.1 => /home/username/epics/base-7.0.6.1/lib/linux-x86_64/libca.so.4.14.1 (0x00007ff83a7dd000)
	libCom.so.3.21.0 => /home/username/epics/base-7.0.6.1/lib/linux-x86_64/libCom.so.3.21.0 (0x00007ff83a567000)
	libautomation1compiler.so => /home/username/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libautomation1compiler.so (0x00007ff83bc65000)
	libautomation1c.so => /home/username/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libautomation1c.so (0x00007ff839f30000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff839b9b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff839819000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff839601000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff83923e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff83901e000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007ff838dcf000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff838bc7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff8389c3000)
	libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007ff838790000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007ff838538000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff83bc09000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007ff83830b000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007ff8380b6000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007ff837dcd000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007ff837bb6000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007ff8379b0000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007ff83779f000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007ff83759b000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007ff8370b5000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff836e9e000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ff836c72000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff836a5b000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007ff8367d7000)

</details>

**EPICS base**: ``SHARED_LIBRARIES=YES`` and ``STATIC_BUILD=NO``
**motorAutomation1**: ``STATIC_BUILD=YES`` in CONFIG_SITE.local
**Result**: automation1 IOC depends only on automation1 vendor libraries

<details>
  <summary>$ ldd iocs/automation1IOC/bin/linux-x86_64/automation1</summary>
  
	linux-vdso.so.1 (0x00007fff2bf84000)
	libautomation1compiler.so => /home/username/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libautomation1compiler.so (0x00007ff3f41ae000)
	libautomation1c.so => /home/username/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libautomation1c.so (0x00007ff3f3b17000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff3f38f7000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007ff3f36a8000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff3f34a0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff3f329c000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff3f2f07000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff3f2b85000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff3f296d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff3f25aa000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007ff3f2352000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff3f414e000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007ff3f2125000)

</details>


**EPICS base**: ``SHARED_LIBRARIES=NO`` and ``STATIC_BUILD=YES``
**motorAutomation1**: no shared/static overrides
**Result**: automation1 IOC depends only on automation1 vendor libraries

<details>
  <summary>$ ldd iocs/automation1IOC/bin/linux-x86_64/automation1</summary>
 
	linux-vdso.so.1 (0x00007ffdeed24000)
	libautomation1compiler.so => /home/username/epics/motor-devel/current/motorAutomation1-static/lib/linux-x86_64/libautomation1compiler.so (0x00007fb6affe1000)
	libautomation1c.so => /home/username/epics/motor-devel/current/motorAutomation1-static/lib/linux-x86_64/libautomation1c.so (0x00007fb6af94a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb6af72a000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007fb6af4db000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fb6af2d3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb6af0cf000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb6aed3a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb6ae9b8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb6ae7a0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb6ae3dd000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007fb6ae185000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6aff81000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fb6adf58000)

</details>

**EPICS base**: ``SHARED_LIBRARIES=NO`` and ``STATIC_BUILD=YES``
**motorAutomation1**: ``STATIC_BUILD=NO`` in CONFIG_SITE.local
**Result**: automation1 IOC depends on automation1 vendor libraries **_and_** motorAutomation1 shared library

<details>
  <summary>$ ldd iocs/automation1IOC/bin/linux-x86_64/automation1</summary>
  
	linux-vdso.so.1 (0x00007ffc265fe000)
	libAutomation1.so => /home/username/epics/motor-devel/current/motorAutomation1-static/lib/linux-x86_64/libAutomation1.so (0x00007fe179e54000)
	libautomation1compiler.so => /home/username/epics/motor-devel/current/motorAutomation1-static/lib/linux-x86_64/libautomation1compiler.so (0x00007fe17a21f000)
	libautomation1c.so => /home/username/epics/motor-devel/current/motorAutomation1-static/lib/linux-x86_64/libautomation1c.so (0x00007fe17981d000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe179488000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe179106000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe178eee000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe178b2b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe17890b000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007fe1786bc000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe1784b4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe1782b0000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007fe178058000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe17a1bf000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fe177e2b000)

</details>

**Review by MarkRivers — COMMENTED** [review]
On line 29 in App/src/Makeufle you might want to leave it inside the ifeq for linux-x86_64, but change to Automation1_SYS_LIBS rather than Automation1_LIBS.  Otherwise you can get errors when building on Linux architectures other than linux-x86_64 (e.g. 32-bit or arm). Same thing for line 51 in iocs Makefile.

**Comment by kmpeters** [comment]
Thanks for the suggestion, @MarkRivers.  I'll need to think about it.  The build also crashes on RHEL7.  I don't know how to protect against that.

I like the ``PROD_SYS_LIBS_Linux`` approach because it doesn't require modifying Makefiles when building for custom linux architectures (rhel8-x86_64).

**Comment by MarkRivers** [comment]
> The build also crashes on RHEL7. I don't know how to protect against that.

Why does it crash?

>I like the PROD_SYS_LIBS_Linux approach because it doesn't require modifying Makefiles when building for custom linux architectures (rhel8-x86_64).

I name my RHEL8 arch linux-x86_64-rhel8.  Then it would work, because it does contain the string linux-x86_64.

**Comment by kmpeters** [comment]
> Why does it crash?

The vendor libraries were built against a version of libstdc++.so that isn't present on our RHEL7 systems:
```
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `std::basic_filebuf<char, std::char_traits<char> >::operator=(std::basic_filebuf<char, std::char_traits<char> >&&)@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1c.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1c.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1c.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `std::__codecvt_utf8_base<wchar_t>::do_max_length() const@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so: undefined reference to `std::ios_base::_M_swap(std::ios_base&)@GLIBCXX_3.4.21'
/home/username/development/epics-motor/motorAutomation1/bin/linux-x86_64/libautomation1c.so: undefined reference to `std::__cxx11::numpunct<char> const& std::use_facet<std::__cxx11::numpunct<char> >(std::locale const&)@GLIBCXX_3.4.21'
```
```
$ strings /usr/lib64/libstdc++.so.6.0.19 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Note: You have to add ``-std=c++11`` to the automation1App/src/Makefile to resolve a missing std::vector shrink_to_fit method problem before you get to the libstdc++ errors.

**Comment by kmpeters** [comment]
@MarkRivers, I moved the vendor libs back to the ifeq/endif block, as you suggested.  If there are no more suggestions, I'll merge this pull request.

**Review by MarkRivers — COMMENTED** [review]
Looks good to me.

**Pull request merged**
